name: Build Workflow
on:
  push:
   branches:
     - 'master'
     - 'develop'
  pull_request:
      types: [opened, synchronize, reopened]
jobs:
  build-package:
    strategy:
      matrix:
        include:
          - architecture: x64
            ubuntu: bionic
            build: true
          - architecture: x64
            ubuntu: focal
            build: true
          - architecture: x64
            ubuntu: jammy
            build: true
          - architecture: armhf
            ubuntu: focal
            build: false
          - architecture: armhf
            ubuntu: jammy
            build: false
          - architecture: arm64
            ubuntu: focal
            build: false
          - architecture: arm64
            ubuntu: jammy
            build: false
    uses: usdot-fhwa-stol/actions/.github/workflows/cpp-module-build.yml@main
    with:
      bucket-codename: ${{ matrix.ubuntu }}
      build: ${{ matrix.build }}
      build-architecture: ${{ matrix.architecture }}
      build-image-tag: ${{ matrix.ubuntu }}
    secrets:
      aws-access-key-id: ${{ secrets.APT_REPO_AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.APT_REPO_AWS_SECRET_ACCESS_KEY }}
