on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
   branches:
     - 'master'
     - 'develop'
  pull_request:
      types: [opened, synchronize, reopened]
name: Sonar Workflow
jobs:
  sonarcloud:
    uses: usdot-fhwa-stol/actions/.github/workflows/sonar-scanner-cpp.yml@main
    with:
      sonar-project-key: usdot-fhwa-stol_multiple-object-tracking
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      sonarcloud-token: ${{ secrets.SONAR_TOKEN }}
